server:
  port: 8077
#173.82.131.169
spring:
  datasource:
    url: jdbc:mysql://173.82.131.169:3306/crud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 173.82.131.169
    port: 6379  #可不配，因为底层默认值为6379
    password: 12345
    database: 0
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

#redis:
#    url: 173.82.131.169
#    database: 0
#    password: 12345
#redis:
#   url: 173.82.131.169
#   database: 0
#   host: root
#   password: 12345
